/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.com.kodfarki.subscreasy.client;
using IO.Swagger.com.kodfarki.subscreasy.client.model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BankAccountResourceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BankAccountResourceApiTests
    {
        private BankAccountResourceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BankAccountResourceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BankAccountResourceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BankAccountResourceApi
            //Assert.IsInstanceOfType(typeof(BankAccountResourceApi), instance, "instance is a BankAccountResourceApi");
        }

        
        /// <summary>
        /// Test CreateBankAccountUsingPOST
        /// </summary>
        [Test]
        public void CreateBankAccountUsingPOSTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BankAccount bankAccount = null;
            //var response = instance.CreateBankAccountUsingPOST(bankAccount);
            //Assert.IsInstanceOf<BankAccount> (response, "response is BankAccount");
        }
        
        /// <summary>
        /// Test DeleteBankAccountUsingDELETE
        /// </summary>
        [Test]
        public void DeleteBankAccountUsingDELETETest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.DeleteBankAccountUsingDELETE(id);
            
        }
        
        /// <summary>
        /// Test GetAllBankAccountsUsingGET
        /// </summary>
        [Test]
        public void GetAllBankAccountsUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAllBankAccountsUsingGET();
            //Assert.IsInstanceOf<List<BankAccount>> (response, "response is List<BankAccount>");
        }
        
        /// <summary>
        /// Test GetBankAccountUsingGET
        /// </summary>
        [Test]
        public void GetBankAccountUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetBankAccountUsingGET(id);
            //Assert.IsInstanceOf<BankAccount> (response, "response is BankAccount");
        }
        
        /// <summary>
        /// Test UpdateBankAccountUsingPUT
        /// </summary>
        [Test]
        public void UpdateBankAccountUsingPUTTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BankAccount bankAccount = null;
            //var response = instance.UpdateBankAccountUsingPUT(bankAccount);
            //Assert.IsInstanceOf<BankAccount> (response, "response is BankAccount");
        }
        
    }

}
