/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.com.kodfarki.subscreasy.client;
using IO.Swagger.com.kodfarki.subscreasy.client.model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StartSubscriptionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StartSubscriptionRequestTests
    {
        // TODO uncomment below to declare an instance variable for StartSubscriptionRequest
        //private StartSubscriptionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StartSubscriptionRequest
            //instance = new StartSubscriptionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StartSubscriptionRequest
        /// </summary>
        [Test]
        public void StartSubscriptionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StartSubscriptionRequest
            //Assert.IsInstanceOfType<StartSubscriptionRequest> (instance, "variable 'instance' is a StartSubscriptionRequest");
        }


        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Test]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Test]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'CouponCode'
        /// </summary>
        [Test]
        public void CouponCodeTest()
        {
            // TODO unit test for the property 'CouponCode'
        }
        /// <summary>
        /// Test the property 'Offer'
        /// </summary>
        [Test]
        public void OfferTest()
        {
            // TODO unit test for the property 'Offer'
        }
        /// <summary>
        /// Test the property 'PaymentCard'
        /// </summary>
        [Test]
        public void PaymentCardTest()
        {
            // TODO unit test for the property 'PaymentCard'
        }
        /// <summary>
        /// Test the property 'Subscriber'
        /// </summary>
        [Test]
        public void SubscriberTest()
        {
            // TODO unit test for the property 'Subscriber'
        }

    }

}
