/* 
 * Api Documentation
 *
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.com.kodfarki.subscreasy.client.model;

namespace IO.Swagger.com.kodfarki.subscreasy.client
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IServiceOfferingResourceApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// createServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>ServiceOffering</returns>
        ServiceOffering CreateServiceOfferingUsingPOST (ServiceOffering serviceOffering);

        /// <summary>
        /// createServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>ApiResponse of ServiceOffering</returns>
        ApiResponse<ServiceOffering> CreateServiceOfferingUsingPOSTWithHttpInfo (ServiceOffering serviceOffering);
        /// <summary>
        /// deleteServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns></returns>
        void DeleteServiceOfferingUsingDELETE (long? id);

        /// <summary>
        /// deleteServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteServiceOfferingUsingDELETEWithHttpInfo (long? id);
        /// <summary>
        /// getAllServiceOfferings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ServiceOffering&gt;</returns>
        List<ServiceOffering> GetAllServiceOfferingsUsingGET ();

        /// <summary>
        /// getAllServiceOfferings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ServiceOffering&gt;</returns>
        ApiResponse<List<ServiceOffering>> GetAllServiceOfferingsUsingGETWithHttpInfo ();
        /// <summary>
        /// getServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>ServiceOffering</returns>
        ServiceOffering GetServiceOfferingUsingGET (long? id);

        /// <summary>
        /// getServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>ApiResponse of ServiceOffering</returns>
        ApiResponse<ServiceOffering> GetServiceOfferingUsingGETWithHttpInfo (long? id);
        /// <summary>
        /// updateServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>ServiceOffering</returns>
        ServiceOffering UpdateServiceOfferingUsingPUT (ServiceOffering serviceOffering);

        /// <summary>
        /// updateServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>ApiResponse of ServiceOffering</returns>
        ApiResponse<ServiceOffering> UpdateServiceOfferingUsingPUTWithHttpInfo (ServiceOffering serviceOffering);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// createServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>Task of ServiceOffering</returns>
        System.Threading.Tasks.Task<ServiceOffering> CreateServiceOfferingUsingPOSTAsync (ServiceOffering serviceOffering);

        /// <summary>
        /// createServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>Task of ApiResponse (ServiceOffering)</returns>
        System.Threading.Tasks.Task<ApiResponse<ServiceOffering>> CreateServiceOfferingUsingPOSTAsyncWithHttpInfo (ServiceOffering serviceOffering);
        /// <summary>
        /// deleteServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteServiceOfferingUsingDELETEAsync (long? id);

        /// <summary>
        /// deleteServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteServiceOfferingUsingDELETEAsyncWithHttpInfo (long? id);
        /// <summary>
        /// getAllServiceOfferings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ServiceOffering&gt;</returns>
        System.Threading.Tasks.Task<List<ServiceOffering>> GetAllServiceOfferingsUsingGETAsync ();

        /// <summary>
        /// getAllServiceOfferings
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ServiceOffering&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ServiceOffering>>> GetAllServiceOfferingsUsingGETAsyncWithHttpInfo ();
        /// <summary>
        /// getServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>Task of ServiceOffering</returns>
        System.Threading.Tasks.Task<ServiceOffering> GetServiceOfferingUsingGETAsync (long? id);

        /// <summary>
        /// getServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>Task of ApiResponse (ServiceOffering)</returns>
        System.Threading.Tasks.Task<ApiResponse<ServiceOffering>> GetServiceOfferingUsingGETAsyncWithHttpInfo (long? id);
        /// <summary>
        /// updateServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>Task of ServiceOffering</returns>
        System.Threading.Tasks.Task<ServiceOffering> UpdateServiceOfferingUsingPUTAsync (ServiceOffering serviceOffering);

        /// <summary>
        /// updateServiceOffering
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>Task of ApiResponse (ServiceOffering)</returns>
        System.Threading.Tasks.Task<ApiResponse<ServiceOffering>> UpdateServiceOfferingUsingPUTAsyncWithHttpInfo (ServiceOffering serviceOffering);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ServiceOfferingResourceApi : IServiceOfferingResourceApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceOfferingResourceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ServiceOfferingResourceApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceOfferingResourceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ServiceOfferingResourceApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// createServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>ServiceOffering</returns>
        public ServiceOffering CreateServiceOfferingUsingPOST (ServiceOffering serviceOffering)
        {
             ApiResponse<ServiceOffering> localVarResponse = CreateServiceOfferingUsingPOSTWithHttpInfo(serviceOffering);
             return localVarResponse.Data;
        }

        /// <summary>
        /// createServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>ApiResponse of ServiceOffering</returns>
        public ApiResponse< ServiceOffering > CreateServiceOfferingUsingPOSTWithHttpInfo (ServiceOffering serviceOffering)
        {
            // verify the required parameter 'serviceOffering' is set
            if (serviceOffering == null)
                throw new ApiException(400, "Missing required parameter 'serviceOffering' when calling ServiceOfferingResourceApi->CreateServiceOfferingUsingPOST");

            var localVarPath = "/api/service-offerings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (serviceOffering != null && serviceOffering.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(serviceOffering); // http body (model) parameter
            }
            else
            {
                localVarPostBody = serviceOffering; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateServiceOfferingUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServiceOffering>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServiceOffering) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServiceOffering)));
        }

        /// <summary>
        /// createServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>Task of ServiceOffering</returns>
        public async System.Threading.Tasks.Task<ServiceOffering> CreateServiceOfferingUsingPOSTAsync (ServiceOffering serviceOffering)
        {
             ApiResponse<ServiceOffering> localVarResponse = await CreateServiceOfferingUsingPOSTAsyncWithHttpInfo(serviceOffering);
             return localVarResponse.Data;

        }

        /// <summary>
        /// createServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>Task of ApiResponse (ServiceOffering)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ServiceOffering>> CreateServiceOfferingUsingPOSTAsyncWithHttpInfo (ServiceOffering serviceOffering)
        {
            // verify the required parameter 'serviceOffering' is set
            if (serviceOffering == null)
                throw new ApiException(400, "Missing required parameter 'serviceOffering' when calling ServiceOfferingResourceApi->CreateServiceOfferingUsingPOST");

            var localVarPath = "/api/service-offerings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (serviceOffering != null && serviceOffering.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(serviceOffering); // http body (model) parameter
            }
            else
            {
                localVarPostBody = serviceOffering; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateServiceOfferingUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServiceOffering>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServiceOffering) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServiceOffering)));
        }

        /// <summary>
        /// deleteServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns></returns>
        public void DeleteServiceOfferingUsingDELETE (long? id)
        {
             DeleteServiceOfferingUsingDELETEWithHttpInfo(id);
        }

        /// <summary>
        /// deleteServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteServiceOfferingUsingDELETEWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ServiceOfferingResourceApi->DeleteServiceOfferingUsingDELETE");

            var localVarPath = "/api/service-offerings/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteServiceOfferingUsingDELETE", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// deleteServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteServiceOfferingUsingDELETEAsync (long? id)
        {
             await DeleteServiceOfferingUsingDELETEAsyncWithHttpInfo(id);

        }

        /// <summary>
        /// deleteServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteServiceOfferingUsingDELETEAsyncWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ServiceOfferingResourceApi->DeleteServiceOfferingUsingDELETE");

            var localVarPath = "/api/service-offerings/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteServiceOfferingUsingDELETE", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// getAllServiceOfferings 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ServiceOffering&gt;</returns>
        public List<ServiceOffering> GetAllServiceOfferingsUsingGET ()
        {
             ApiResponse<List<ServiceOffering>> localVarResponse = GetAllServiceOfferingsUsingGETWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// getAllServiceOfferings 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ServiceOffering&gt;</returns>
        public ApiResponse< List<ServiceOffering> > GetAllServiceOfferingsUsingGETWithHttpInfo ()
        {

            var localVarPath = "/api/service-offerings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllServiceOfferingsUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ServiceOffering>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ServiceOffering>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ServiceOffering>)));
        }

        /// <summary>
        /// getAllServiceOfferings 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ServiceOffering&gt;</returns>
        public async System.Threading.Tasks.Task<List<ServiceOffering>> GetAllServiceOfferingsUsingGETAsync ()
        {
             ApiResponse<List<ServiceOffering>> localVarResponse = await GetAllServiceOfferingsUsingGETAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// getAllServiceOfferings 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ServiceOffering&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ServiceOffering>>> GetAllServiceOfferingsUsingGETAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/service-offerings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllServiceOfferingsUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ServiceOffering>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ServiceOffering>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ServiceOffering>)));
        }

        /// <summary>
        /// getServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>ServiceOffering</returns>
        public ServiceOffering GetServiceOfferingUsingGET (long? id)
        {
             ApiResponse<ServiceOffering> localVarResponse = GetServiceOfferingUsingGETWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// getServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>ApiResponse of ServiceOffering</returns>
        public ApiResponse< ServiceOffering > GetServiceOfferingUsingGETWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ServiceOfferingResourceApi->GetServiceOfferingUsingGET");

            var localVarPath = "/api/service-offerings/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetServiceOfferingUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServiceOffering>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServiceOffering) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServiceOffering)));
        }

        /// <summary>
        /// getServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>Task of ServiceOffering</returns>
        public async System.Threading.Tasks.Task<ServiceOffering> GetServiceOfferingUsingGETAsync (long? id)
        {
             ApiResponse<ServiceOffering> localVarResponse = await GetServiceOfferingUsingGETAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// getServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">id</param>
        /// <returns>Task of ApiResponse (ServiceOffering)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ServiceOffering>> GetServiceOfferingUsingGETAsyncWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling ServiceOfferingResourceApi->GetServiceOfferingUsingGET");

            var localVarPath = "/api/service-offerings/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetServiceOfferingUsingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServiceOffering>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServiceOffering) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServiceOffering)));
        }

        /// <summary>
        /// updateServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>ServiceOffering</returns>
        public ServiceOffering UpdateServiceOfferingUsingPUT (ServiceOffering serviceOffering)
        {
             ApiResponse<ServiceOffering> localVarResponse = UpdateServiceOfferingUsingPUTWithHttpInfo(serviceOffering);
             return localVarResponse.Data;
        }

        /// <summary>
        /// updateServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>ApiResponse of ServiceOffering</returns>
        public ApiResponse< ServiceOffering > UpdateServiceOfferingUsingPUTWithHttpInfo (ServiceOffering serviceOffering)
        {
            // verify the required parameter 'serviceOffering' is set
            if (serviceOffering == null)
                throw new ApiException(400, "Missing required parameter 'serviceOffering' when calling ServiceOfferingResourceApi->UpdateServiceOfferingUsingPUT");

            var localVarPath = "/api/service-offerings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (serviceOffering != null && serviceOffering.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(serviceOffering); // http body (model) parameter
            }
            else
            {
                localVarPostBody = serviceOffering; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateServiceOfferingUsingPUT", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServiceOffering>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServiceOffering) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServiceOffering)));
        }

        /// <summary>
        /// updateServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>Task of ServiceOffering</returns>
        public async System.Threading.Tasks.Task<ServiceOffering> UpdateServiceOfferingUsingPUTAsync (ServiceOffering serviceOffering)
        {
             ApiResponse<ServiceOffering> localVarResponse = await UpdateServiceOfferingUsingPUTAsyncWithHttpInfo(serviceOffering);
             return localVarResponse.Data;

        }

        /// <summary>
        /// updateServiceOffering 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceOffering">serviceOffering</param>
        /// <returns>Task of ApiResponse (ServiceOffering)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ServiceOffering>> UpdateServiceOfferingUsingPUTAsyncWithHttpInfo (ServiceOffering serviceOffering)
        {
            // verify the required parameter 'serviceOffering' is set
            if (serviceOffering == null)
                throw new ApiException(400, "Missing required parameter 'serviceOffering' when calling ServiceOfferingResourceApi->UpdateServiceOfferingUsingPUT");

            var localVarPath = "/api/service-offerings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (serviceOffering != null && serviceOffering.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(serviceOffering); // http body (model) parameter
            }
            else
            {
                localVarPostBody = serviceOffering; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateServiceOfferingUsingPUT", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ServiceOffering>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ServiceOffering) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ServiceOffering)));
        }

    }
}
